name: dota2_invoker_game
description: DOTA 2 Invoker practice game.

publish_to: 'none'

version: 1.9.0+33

environment:
  sdk: '>=3.0.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  #State Management
  provider: ^6.1.5+1

  #Localization
  easy_localization: ^3.0.8

  #Icons
  font_awesome_flutter: ^11.0.0
  cupertino_icons: ^1.0.9

  #Utils
  flutter_svg: ^2.3.0
  flutter_soloud: ^5.1.2
  internet_connection_checker: ^1.0.0+1
  url_launcher: ^6.3.2
  auto_size_text: ^3.0.0
  flutter_fgbg: ^0.8.0
  tuple: ^2.0.2
  collection: ^1.19.1

  #.env
  flutter_dotenv: ^6.0.1

  #Local Storage
  hive_ce: ^2.20.0
  hive_ce_flutter: ^2.3.4
  shared_preferences: ^2.5.5

  #Firebase
  firebase_core: ^4.15.0
  cloud_firestore: ^6.10.0
  firebase_auth: ^6.7.0
  firebase_remote_config: ^6.7.0
  firebase_analytics: ^12.6.0

  #Animation
  lottie: ^3.6.1
  splash: ^1.2.0
  flutter_animate: ^4.5.2
  animated_flip_counter: ^0.3.4
  snappable_thanos:
    git:
      url: https://github.com/tolgasozbir/snappable_thanos.git
      ref: main

  #Widgets
  sleek_circular_slider: ^2.1.0
  reorderable_grid: ^1.0.13
  percent_indicator: ^4.2.5

  #Ads
  google_mobile_ads: ^9.1.0

  #IAP
  purchases_flutter: ^10.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  #Lint
  very_good_analysis: ^10.3.0
  #Hive
  hive_ce_generator: ^1.11.3
  #
  build_runner: ^2.16.1


flutter:
  uses-material-design: true

  fonts:
    - family: Virgil
      fonts:
        - asset: assets/fonts/Virgil.ttf
          weight: 400

  assets:
    # Environment configuration
    - .env

    # Localization
    - assets/lang/

    # Animations & Graphics
    - assets/icons/
    - assets/lottie/
    - assets/svg/

    # Images
    - assets/images/qwe_gifs/
    - assets/images/misc/
    - assets/images/elements/
    - assets/images/spells/
    - assets/images/achievements/
    - assets/images/bosses/
    - assets/images/items/

    # Sounds
    ## Invoker Responses
    - assets/sounds/ability_cooldown/default/
    - assets/sounds/ability_cooldown/persona/
    - assets/sounds/fail_cast/default/
    - assets/sounds/fail_cast/persona/
    - assets/sounds/game_over/default/
    - assets/sounds/game_over/persona/
    - assets/sounds/insufficient_mana/default/
    - assets/sounds/insufficient_mana/persona/
    - assets/sounds/loading/default/
    - assets/sounds/loading/persona/

    ## Item Sounds
    - assets/sounds/item/
    ## Miscellaneous Sounds
    - assets/sounds/misc/
    ## Shop Sounds
    - assets/sounds/shop/
    ## Spell Sounds
    - assets/sounds/spell/
    - assets/sounds/spell/cast/

    ##Boss Sounds
    - assets/sounds/boss/warlock/
    - assets/sounds/boss/omniknight/
    - assets/sounds/boss/riki/
    - assets/sounds/boss/huskar/
    - assets/sounds/boss/templar/
    - assets/sounds/boss/anti_mage/
    - assets/sounds/boss/juggernaut/
    - assets/sounds/boss/blood_seeker/
    - assets/sounds/boss/blood_seeker/
    - assets/sounds/boss/drow_ranger/
    - assets/sounds/boss/axe/
    - assets/sounds/boss/pudge/
    - assets/sounds/boss/wraith_king/